export const AuthTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
};

export const ResourceType = {
  ADD_RESOURCE_REQUEST: "ADD_RESOURCE_REQUEST",
  ADD_RESOURCE_FAILURE: "ADD_RESOURCE_FAILURE",
  ADD_RESOURCE_SUCCESS: "ADD_RESOURCE_SUCCESS",
};

export const ProjectType = {
  ADD_PROJECT_REQUEST: "ADD_PROJECT_REQUEST",
  ADD_PROJECT_FAILURE: "ADD_PROJECT_FAILURE",
  ADD_PROJECT_SUCCESS: "ADD_PROJECT_SUCCESS",

  GET_ALL_PROJECT_REQUEST: "GET_ALL_PROJECT_REQUEST",
  GET_ALL_PROJECT_FAILURE: "GET_ALL_PROJECT_FAILURE",
  GET_ALL_PROJECT_SUCCESS: "GET_ALL_PROJECT_SUCCESS",
};
